### ISSUE TITLE
HA overwrites additional  attributes and App doesn't get retriggered

### ISSUE THREAD

**Issue by Mariusthvdb** [ludeeus/ad-address#3]
This has been working for a long time now, to great satisfaction and use.
Something has changed however, maybe in core HA handling device_trackers?

This is what I am experiencing: Initially the app adds the extra attributes just fine. Somehow though HA  (in version 117, might have been 116 too already) updates the device_trackers, so these additional attributes are taken away again.

The App here doesn't retrigger though. 

This happens if the tracker isnt moving.

Upon a real gps update, the AD app retriggers, adding the additional attributes once again. Only to have them be overwritten shortly thereafter by core HA..

Could this core triggering be a bug, or if not, be mitigated in the AD app to retrigger upon losing the attributes (eg country code, which is always added)?

Thanks for having a look.

**Comment by ReneTode** [comment]
set_state for entities in HA is always buggy.
if HA updates the device tracker, thats probably because an attribute changed, so you could listen for that.
at least there should be an event when the device tracker is changed by HA.

i wonder which attributes you personally add, because there might be better ways.
normally you should the device_tracker/see service to update a devicetracker.

another option would be to create new devicetrackers, that you update when the original device tracker is updated, and set your own attributes on that. and hide the original devicetrackers.

**Comment by Mariusthvdb** [comment]
> if HA updates the device tracker, thats probably because an attribute changed, so you could listen for that.
> at least there should be an event when the device tracker is changed by HA.

correct, I see it happen at a last_seen change, or eg the battery.

> normally you should the device_tracker/see service to update a devicetracker.
Ive thought about that, but its not a solution I believe, because the 'seeing' of the Device_tracker causes HA to overwrite the state, (and ditch the additional attributes)

This didnt happen before, something must have changed in the way HA uses device_trackers lately?

> another option would be to create new devicetrackers,

tbh, that's how this all started of in the beginning, and then Luduees thought it best to simply add the attributes to the existing device_tracker.

Id be very interested in doing that, because the full set of attributes this App ads is very complete, and I would love to have these permanently in the system...

**Comment by ReneTode** [comment]
could very well be that HA changed something. AD didnt change ;) 

but you can adapt your app, by adding more listeners or using other device_trackers. what and how you do it is up to you.

**Comment by Mariusthvdb** [comment]
could it also be adapted to update if the attribute country_code isn't set? meanwhile I am testing the creation of another device_tracker (mqtt) based on only the gps coordinates, and see what that does.

__update__

even using a device_tracker.marijn_location
```
device_tracker:
  - platform: mqtt_json
    devices:
      marijn_location: location_only/marijn
```

 made by this automation:
```
      - service: mqtt.publish
        data:
          topic: location_only/marijn
          retain: true
          payload: >-
            {
              "latitude": "{{trigger.to_state.attributes.latitude}}",
              "longitude": "{{trigger.to_state.attributes.longitude}}"
            }
```
the address is added correctly, after which it is overwritten quite swiftly by the HA system unfortunately.
and 
btw, I am unsure what yo mean exactly using the[ input_boolean, and how to force an AD app call back/update](https://community.home-assistant.io/t/home-assistant-community-add-on-appdaemon-4/163259/99?u=mariusthvdb) with that. I mean, I understand how to write an automation based on state changes of the device_trackers, but wouldn't know which service to call, to update the AD app?

**Comment by ReneTode** [comment]
first off all i wasnt talking about creating a device tracker in HA (because you would still have the same trouble)
i was talking about creating a device tracker with an AD app. (and not with mqtt)

i guess you use AD, but dont understand it, or know how to use it?
if you have an input boolean in HA then you can use listen_state to listen to the state change from that boolean.
then you can do everything you want in the callback from that listen_state

you dont need services for that. just a boolean and a listen_state

but its really easier if you come to our discord server, to talk about those things, so that we can give you guidelines.

**Comment by Mariusthvdb** [comment]
ok thanks, and yes, I am a noob in AD, only using 2 apps. This being one of them, which has stopped being reliable since 116/117.

even if I would add more listeners, causing more frequent runs of the app, that might be not the final solution to this issue wouldn't it? It would  cause a serious spike (if not a loop) in the system, and be continuously running.

this is an issue for this small gem for now, so should really be mitigated either here, or, if its a more generic thing introduced in HA, be issued in GitHub HA core.

btw, following your advise above, I have added more device_trackers to the app as you suggested, and they all see the same result: start off with a full set of additional attributes, which are then deleted shortly after. So I took them out again, to save some processor %...

**Comment by ludeeus** [comment]
What you are describing is how this hack always worked.
It infuses the current set with additional attributes when a state changes happens.
Modifications done on the state API has always been lost on state changes, this is not new.

TBH no one should be using this app, it's bad.
The companion apps for iOS/Android already have this information natively.

**Comment by Mariusthvdb** [comment]
yeah, I understand how this app works, adding the attributes. But it is as you say 'when a state change happens'.

Currently the device_trackers seem to update even without a statechange, breaking this functionality. Which is unexpected  behavior for a device_tracker in the first place.

Also, the companion app needs to be installed for that, and how odd it might seem, not everyone has that installed ;-) And that is not even mentioning the AD app offers more detailed info.

Not to interfere with the core device_trackers, maybe a change in the Ad app could be made to create a sensor using the same object_id with the state/attributes? That would then stick, until a lat/long change occurs again.

**Comment by ReneTode** [comment]
the problem is that you use an app from someone else and dont know how to change it correctly.
like ludeeus says, it was always hacking HA in a way that wasnt supported.
that it now stopped working cant be helped by AD, because it shouldnt be used in that way in the first place.

so you could ask someone else to change the app, or you could learn how to change it yourself.
indeed its possible to create sensors (or even devicetrackers) that are not touched by HA, because HA doesnt know them when they are created by AD. HA will never update those sensors or devicetrackers.

or you could find a different way to get what you want.

oeps, didnt realise this wasnt the AD github ;) 
but the answer stays the same.
if the creator from the app says it shouldnt be used (anymore) youll need to figure out something else yourself, when it stops working ;)

**Comment by Mariusthvdb** [comment]
Well, yeah thanks. You state many things, all true, but all known..... 

Of course I ask here, because I dont know how to do so myself. Also, because this app was made by Ludeeus as a solution/result for a question I posted in the first place. I clearly remember the opening post where he said this was his first AD app, and I applauded him for helping me that way. ;-)

So, (though I also posted an issue on the HA core device_tracker GitHub oof this can be caused by an internal HA change), I really am asking for help, to adapt this AD app from infusing the tracked device_tracker with the additional attributes, to creating a new entity (either device_tracker, or sensor) with the same set of attributes. 

If this is very easy for you, might I ask you could help me out?
Ive started with some code copying, but this is still full of errors:
```
     def set_new_sensor_state(self, state):
         """Create/Publish a new state for the sensor based on the tracked device_trackers attributes."""
         attributes = self.get_state(entity, attribute="all")["attributes"]
         state = self.get_state(entity)
         object = state.split('.')[1]
         sensor = 'sensor.{}'.format(object)
         for attr in raw:
             attributes[attr] = raw[attr]

         self.set_state(sensor, state=state, attributes=attributes)
```

the rest of the app could remain because it would still need to be triggered by the same gps changes. Guess the original 
```
        self.log("Updating state for {}".format(entity))
        self.set_state(entity, state = state, attributes = attributes)
```
could be taken out, as it wouldn't need to infuse the tracked device_trackers any longer.

**Comment by ReneTode** [comment]
to create new device trackers, that have the same attributes and get updated, but not overwritten, you only need to change 1 thing.
the last line from the new app.
```
self.set_state(entity, state = state, attributes=attributes)
```
if you change that to:
```
self.set_state("{}_{}".format(entity,"2"), state = state, attributes=attributes)
```

then for every device_tracker you listen to with the app there will be a second device_tracker created with the name device_tracker.name_2
that entity is then created by AD and wont be touched by HA. as soon as HA updates it it should also be updated.

allthough you say the entities are changed by HA and not by AD, so it is possible that you need to add a few more lines
(which might also work without the new devicetrackers)

after line 28:
```
            self.listen_state(self.get_address, entity)
```
you can add lines like:
```
            self.listen_state(self.get_address, entity, attribute = "latitude")
            self.listen_state(self.get_address, entity, attribute = "longitude")
```
those new listeners will make that the callback is also triggered when 1 off those attributes change.

**Comment by Mariusthvdb** [comment]
thanks! that's really helpful indeed. 

Turns out I had an other issue going on too. Since this AD app had stopped working for some time (moving from ad3 to 4) I had help from @burningstone and rebuild the app to this AD 4 version posted below.

In retrying the original, I think I confused the AD system to have both and solely commenting that in the app.yaml seems to not be sufficient, once really needs to take out the app from the apps directory. I noticed that because it stated `no description was found, ignoring... etc etc`

Ive have now adapted the second app made by @burningstone with your last line, creating secondary _address device_trackers, and they still show the additional attributes. #fingerscrossed

thanks Again! Much much appreciated.
```
"""Address AppDaemon app."""
# pylint: disable=attribute-defined-outside-init, unused-argument, too-many-arguments
from geopy.geocoders import Nominatim

import adbase as ad
#
# Address App
# requires: "geopy" https://pypi.org/project/geopy/
#
#
# Args:
#   entity: entity_id of a device_tracker entity, example "device_tracker.my_entity"
#

class Address(ad.ADBase):
    """Address class."""

    def initialize(self):
        """initialize Address."""
        self.adbase = self.get_ad_api()
        self.hass = self.get_plugin_api("HASS")

        self.adbase.log("App started.")
        entities = self.args["entities"]

        if isinstance(entities, str):
            entities = [ent_id.strip() for ent_id in entities.split(",")]

        for entity in entities:
            self.update_address(entity)
            self.hass.listen_state(self.location_change_cb, entity)
            self.adbase.log(f"State listener for {entity} started.")

    def location_change_cb(self, entity, attribute, old, new, kwargs):
        """Update the address on change of location"""
        self.update_address(entity)

    def update_address(self, entity):
        entity_state = self.hass.get_state(entity, attribute="all")
        state = entity_state["state"]
        attributes = entity_state["attributes"]

        latitude = attributes.get("latitude")
        longitude = attributes.get("longitude")

        if not latitude and not longitude:
            self.adbase.log(f"No latitude/longitude attribute found for {entity}")
            return

        # Get address
        geo = Nominatim(user_agent="AppDaemon")
        data = geo.reverse(f"{latitude}, {longitude}")
        raw = data.raw["address"]
        self.adbase.log(raw)

        for attr in raw:
            attributes[attr] = raw[attr]

        self.adbase.log(f"Updating state for {entity}")
        self.adbase.set_state("{}_{}".format(entity,"address"), state=state, attributes=attributes, namespace="default")
#        self.adbase.set_state(entity, state=state, attributes=attributes, namespace="default")  #<-- original line
```

not sure how to format the extra listeners in this config, could you please check that for me once more, like this?

```
            self.listen_state(self.update_address, entity, attribute = "latitude")
            self.listen_state(self.update_address, entity, attribute = "longitude")
```

**Comment by ReneTode** [comment]
self.hass.listen_state(self.location_change_cb, entity, attribute = "latitude")

**Comment by Mariusthvdb** [comment]
thx!
I see it now.... sorry.

working very nicely now and seems to be rock solid.
So closing would be appropriate?

**Comment by ReneTode** [comment]
if your satisfied, i think so.
